apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/test-component--apqe/base
- components/test-component--myfo/base
- components/test-component--xqad/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
